/*
 * This source file was generated by the Gradle 'init' task
 */
package example;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.util.ArrayList;
import java.util.List;
import td2.Card;

import static org.junit.Assert.assertEquals;

public class AppTest {

    @Before
    public void setUp() {

       Card joker = new Card(Card.CardEnum.JOKER);
    }

    @After
    public void tearDown() {
        Card joker = null;
    }

    @Test
    public void colourIsCorrect() {
        assertEquals();
    }

}
